// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserPermissionsManagement.Contexts;

#nullable disable

namespace _.Migrations
{
    [DbContext(typeof(UserPermissionsContext))]
    [Migration("20240620015949_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPermiso")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPermisoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoPermisoId");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoEmpleado = "Perez",
                            FechaPermiso = new DateTime(2024, 6, 19, 20, 59, 48, 842, DateTimeKind.Local).AddTicks(5594),
                            NombreEmpleado = "Juan",
                            TipoPermisoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApellidoEmpleado = "Gomez",
                            FechaPermiso = new DateTime(2024, 6, 19, 20, 59, 48, 842, DateTimeKind.Local).AddTicks(5612),
                            NombreEmpleado = "Maria",
                            TipoPermisoId = 2
                        },
                        new
                        {
                            Id = 3,
                            ApellidoEmpleado = "Rodriguez",
                            FechaPermiso = new DateTime(2024, 6, 19, 20, 59, 48, 842, DateTimeKind.Local).AddTicks(5614),
                            NombreEmpleado = "Pedro",
                            TipoPermisoId = 3
                        });
                });

            modelBuilder.Entity("Models.PermissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermissionType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Vacaciones"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Enfermedad"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Permiso sin goce de sueldo"
                        });
                });

            modelBuilder.Entity("Models.Permission", b =>
                {
                    b.HasOne("Models.PermissionType", "TipoPermiso")
                        .WithMany("Permission")
                        .HasForeignKey("TipoPermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPermiso");
                });

            modelBuilder.Entity("Models.PermissionType", b =>
                {
                    b.Navigation("Permission");
                });
#pragma warning restore 612, 618
        }
    }
}
